version: '3.1'

services:
  web:
    image: unhatched
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
